---
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: enterprise-accounts-log-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: db.enterprise.accounts
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
      properties:
        showHeaders: true
