---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: event-bus
  name: kafka-connect-cluster-status
spec:
  config:
    cleanup.policy: compact
  partitions: 1
  replicas: 3
