---
apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  channel:
    bootstrapServers: event-bus-kafka-bootstrap.kafka-on-ocp-demo.svc:9092
    enabled: true
  source:
    enabled: true
